export interface Event {
  id: string;
  title: string;
  location: {
    city: string;
    state: string;
    locationId: string; // ID from locationsOptions
  };
  date: Date;
  price: number;
  modalities: string[]; // Array of modality IDs
  organizer: string;
  image: string;
  status: "inscricoes-abertas" | "inscricoes-encerradas" | "evento-encerrado";
  description?: string;
}

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Maratona de São Paulo",
    location: {
      city: "São Paulo",
      state: "SP",
      locationId: "sao-paulo",
    },
    date: new Date("2025-03-15"),
    price: 150,
    modalities: ["corrida-de-rua", "42k"],
    organizer: "Maratona SP",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "A maior maratona da cidade de São Paulo",
  },
  {
    id: "2",
    title: "Corrida da Praia de Copacabana",
    location: {
      city: "Rio de Janeiro",
      state: "RJ",
      locationId: "rio-de-janeiro",
    },
    date: new Date("2025-04-20"),
    price: 80,
    modalities: ["corrida-de-rua", "praia", "de-5k-a-10k"],
    organizer: "Corrida Rio",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Corrida pela orla de Copacabana",
  },
  {
    id: "3",
    title: "Triathlon de Belo Horizonte",
    location: {
      city: "Belo Horizonte",
      state: "MG",
      locationId: "belo-horizonte",
    },
    date: new Date("2025-05-10"),
    price: 350,
    modalities: ["triathlon", "natacao", "ciclismo"],
    organizer: "Triathlon MG",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Prova completa de triathlon",
  },
  {
    id: "4",
    title: "Caminhada Ecológica Brasília",
    location: {
      city: "Brasília",
      state: "DF",
      locationId: "brasilia",
    },
    date: new Date("2025-06-05"),
    price: 50,
    modalities: ["caminhada", "ate-4k"],
    organizer: "Caminhada DF",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Caminhada pela natureza do Distrito Federal",
  },
  {
    id: "5",
    title: "Ciclismo de Montanha Curitiba",
    location: {
      city: "Curitiba",
      state: "PR",
      locationId: "curitiba",
    },
    date: new Date("2025-07-12"),
    price: 120,
    modalities: ["ciclismo", "ciclismo-montanha"],
    organizer: "Ciclismo PR",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Desafio de mountain bike",
  },
  {
    id: "6",
    title: "Corrida Noturna Porto Alegre",
    location: {
      city: "Porto Alegre",
      state: "RS",
      locationId: "porto-alegre",
    },
    date: new Date("2025-08-18"),
    price: 90,
    modalities: ["corrida-de-rua", "corrida-noturna", "de-5k-a-10k"],
    organizer: "Corrida Noturna RS",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Corrida noturna pelas ruas de Porto Alegre",
  },
  {
    id: "7",
    title: "Maratona de Salvador",
    location: {
      city: "Salvador",
      state: "BA",
      locationId: "salvador",
    },
    date: new Date("2025-09-25"),
    price: 180,
    modalities: ["corrida-de-rua", "42k"],
    organizer: "Maratona BA",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Maratona pela cidade histórica",
  },
  {
    id: "8",
    title: "Corrida de Trilha Fortaleza",
    location: {
      city: "Fortaleza",
      state: "CE",
      locationId: "fortaleza",
    },
    date: new Date("2025-10-08"),
    price: 100,
    modalities: ["corrida-trilha", "de-11k-a-20k"],
    organizer: "Trilha CE",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Corrida em trilhas naturais",
  },
  {
    id: "9",
    title: "Natação em Águas Abertas Manaus",
    location: {
      city: "Manaus",
      state: "AM",
      locationId: "manaus",
    },
    date: new Date("2025-11-15"),
    price: 200,
    modalities: ["natacao"],
    organizer: "Natação AM",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Prova de natação em águas abertas",
  },
  {
    id: "10",
    title: "Corrida Virtual Recife",
    location: {
      city: "Recife",
      state: "PE",
      locationId: "recife",
    },
    date: new Date("2025-12-01"),
    price: 60,
    modalities: ["corridas-virtuais", "de-5k-a-10k"],
    organizer: "Corrida Virtual PE",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Corrida virtual, corra de onde estiver",
  },
  {
    id: "11",
    title: "Beach Tennis São Luís",
    location: {
      city: "São Luís",
      state: "MA",
      locationId: "sao-luis",
    },
    date: new Date("2025-04-30"),
    price: 70,
    modalities: ["beach-tennis", "praia"],
    organizer: "Beach Tennis MA",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Torneio de beach tennis",
  },
  {
    id: "12",
    title: "Corrida de Aventura São Paulo",
    location: {
      city: "São Paulo",
      state: "SP",
      locationId: "sao-paulo",
    },
    date: new Date("2025-05-25"),
    price: 250,
    modalities: ["corrida-aventura", "de-11k-a-20k"],
    organizer: "Aventura SP",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Corrida com obstáculos e aventura",
  },
  {
    id: "13",
    title: "Meia Maratona Rio de Janeiro",
    location: {
      city: "Rio de Janeiro",
      state: "RJ",
      locationId: "rio-de-janeiro",
    },
    date: new Date("2025-06-20"),
    price: 130,
    modalities: ["corrida-de-rua", "21k"],
    organizer: "Meia Maratona RJ",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Meia maratona pela cidade maravilhosa",
  },
  {
    id: "14",
    title: "Corrida Só Mulheres Belo Horizonte",
    location: {
      city: "Belo Horizonte",
      state: "MG",
      locationId: "belo-horizonte",
    },
    date: new Date("2025-07-08"),
    price: 75,
    modalities: ["corrida-de-rua", "so-mulheres", "de-5k-a-10k"],
    organizer: "Corrida Mulheres MG",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Corrida exclusiva para mulheres",
  },
  {
    id: "15",
    title: "Ciclismo de Estrada Brasília",
    location: {
      city: "Brasília",
      state: "DF",
      locationId: "brasilia",
    },
    date: new Date("2025-08-14"),
    price: 110,
    modalities: ["ciclismo"],
    organizer: "Ciclismo DF",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Prova de ciclismo de estrada",
  },
  {
    id: "16",
    title: "Corrida de Crianças Curitiba",
    location: {
      city: "Curitiba",
      state: "PR",
      locationId: "curitiba",
    },
    date: new Date("2025-09-10"),
    price: 40,
    modalities: ["criancas", "ate-4k"],
    organizer: "Corrida Kids PR",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Corrida especial para crianças",
  },
  {
    id: "17",
    title: "Uphill Porto Alegre",
    location: {
      city: "Porto Alegre",
      state: "RS",
      locationId: "porto-alegre",
    },
    date: new Date("2025-10-22"),
    price: 95,
    modalities: ["uphill"],
    organizer: "Uphill RS",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Desafio de corrida em subida",
  },
  {
    id: "18",
    title: "Futevôlei Salvador",
    location: {
      city: "Salvador",
      state: "BA",
      locationId: "salvador",
    },
    date: new Date("2025-11-05"),
    price: 85,
    modalities: ["futevolei", "praia"],
    organizer: "Futevôlei BA",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Torneio de futevôlei na praia",
  },
  {
    id: "19",
    title: "Canoagem Vaa Fortaleza",
    location: {
      city: "Fortaleza",
      state: "CE",
      locationId: "fortaleza",
    },
    date: new Date("2025-12-12"),
    price: 160,
    modalities: ["canoagem-vaa"],
    organizer: "Canoagem CE",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Prova de canoagem va'a",
  },
  {
    id: "20",
    title: "Circuito de Corridas Manaus",
    location: {
      city: "Manaus",
      state: "AM",
      locationId: "manaus",
    },
    date: new Date("2025-03-28"),
    price: 140,
    modalities: ["circuito", "corrida-de-rua"],
    organizer: "Circuito AM",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Circuito com múltiplas provas",
  },
  {
    id: "21",
    title: "Grupo Esportivo Recife",
    location: {
      city: "Recife",
      state: "PE",
      locationId: "recife",
    },
    date: new Date("2025-04-15"),
    price: 55,
    modalities: ["grupos-esportivos"],
    organizer: "Grupo PE",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Atividades em grupo",
  },
  {
    id: "22",
    title: "Capacitação Esportiva São Luís",
    location: {
      city: "São Luís",
      state: "MA",
      locationId: "sao-luis",
    },
    date: new Date("2025-05-20"),
    price: 200,
    modalities: ["capacitacao"],
    organizer: "Capacitação MA",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Curso de capacitação esportiva",
  },
  {
    id: "23",
    title: "Maratona de São Paulo - Edição Especial",
    location: {
      city: "São Paulo",
      state: "SP",
      locationId: "sao-paulo",
    },
    date: new Date("2025-06-30"),
    price: 170,
    modalities: ["corrida-de-rua", "42k"],
    organizer: "Maratona SP Especial",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Edição especial da maratona",
  },
  {
    id: "24",
    title: "Corrida de Rua Rio de Janeiro - 10K",
    location: {
      city: "Rio de Janeiro",
      state: "RJ",
      locationId: "rio-de-janeiro",
    },
    date: new Date("2025-07-25"),
    price: 100,
    modalities: ["corrida-de-rua", "de-5k-a-10k"],
    organizer: "Corrida 10K RJ",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Corrida de 10km",
  },
  {
    id: "25",
    title: "Triathlon Belo Horizonte - Sprint",
    location: {
      city: "Belo Horizonte",
      state: "MG",
      locationId: "belo-horizonte",
    },
    date: new Date("2025-08-30"),
    price: 280,
    modalities: ["triathlon"],
    organizer: "Triathlon Sprint MG",
    image: "/banners/card_placeholder.png",
    status: "inscricoes-abertas",
    description: "Triathlon sprint distance",
  },
];

