import type { Registration } from "@/services/organizer/OrganizerService";

export const mockRegistrations: Registration[] = [
  {
    id: "reg-001",
    eventId: "event-1",
    userId: "user-001",
    status: "CONFIRMED",
    totalAmount: 150,
    serviceFee: 7.5,
    finalAmount: 157.5,
    qrCode: "QR-001",
    purchaseDate: "2025-01-15T14:30:00Z",
    user: {
      id: "user-001",
      firstName: "João",
      lastName: "Silva",
      email: "joao.silva@email.com",
      documentNumber: "123.456.789-00",
    },
    modalities: [
      {
        id: "mod-001",
        modality: {
          id: "mod-001",
          eventId: "event-1",
          name: "Corrida 5K",
          price: 80,
          isActive: true,
          order: 1,
          createdAt: "",
          updatedAt: "",
        },
      },
      {
        id: "mod-002",
        modality: {
          id: "mod-002",
          eventId: "event-1",
          name: "Kit Básico",
          price: 70,
          isActive: true,
          order: 2,
          createdAt: "",
          updatedAt: "",
        },
      },
    ],
    kitItems: [],
    questionAnswers: [],
  },
  {
    id: "reg-002",
    eventId: "event-1",
    userId: "user-002",
    status: "CONFIRMED",
    totalAmount: 200,
    serviceFee: 10,
    finalAmount: 210,
    qrCode: "QR-002",
    purchaseDate: "2025-01-18T09:15:00Z",
    user: {
      id: "user-002",
      firstName: "Maria",
      lastName: "Santos",
      email: "maria.santos@email.com",
      documentNumber: "987.654.321-00",
    },
    modalities: [
      {
        id: "mod-003",
        modality: {
          id: "mod-003",
          eventId: "event-1",
          name: "Meia Maratona 21K",
          price: 200,
          isActive: true,
          order: 3,
          createdAt: "",
          updatedAt: "",
        },
      },
    ],
    kitItems: [],
    questionAnswers: [],
  },
  {
    id: "reg-003",
    eventId: "event-1",
    userId: "user-003",
    status: "CONFIRMED",
    totalAmount: 350,
    serviceFee: 17.5,
    finalAmount: 367.5,
    qrCode: "QR-003",
    purchaseDate: "2025-01-10T16:45:00Z",
    user: {
      id: "user-003",
      firstName: "Pedro",
      lastName: "Oliveira",
      email: "pedro.oliveira@email.com",
      documentNumber: "456.789.123-00",
    },
    modalities: [
      {
        id: "mod-004",
        modality: {
          id: "mod-004",
          eventId: "event-1",
          name: "Maratona 42K",
          price: 350,
          isActive: true,
          order: 4,
          createdAt: "",
          updatedAt: "",
        },
      },
    ],
    kitItems: [],
    questionAnswers: [],
  },
  {
    id: "reg-004",
    eventId: "event-1",
    userId: "user-004",
    status: "CANCELLED",
    totalAmount: 80,
    serviceFee: 4,
    finalAmount: 84,
    qrCode: "QR-004",
    purchaseDate: "2025-01-05T11:20:00Z",
    user: {
      id: "user-004",
      firstName: "Ana",
      lastName: "Costa",
      email: "ana.costa@email.com",
      documentNumber: "321.654.987-00",
    },
    modalities: [
      {
        id: "mod-001",
        modality: {
          id: "mod-001",
          eventId: "event-1",
          name: "Corrida 5K",
          price: 80,
          isActive: true,
          order: 1,
          createdAt: "",
          updatedAt: "",
        },
      },
    ],
    kitItems: [],
    questionAnswers: [],
  },
  {
    id: "reg-005",
    eventId: "event-1",
    userId: "user-005",
    status: "COMPLETED",
    totalAmount: 130,
    serviceFee: 6.5,
    finalAmount: 136.5,
    qrCode: "QR-005",
    purchaseDate: "2024-12-20T08:00:00Z",
    user: {
      id: "user-005",
      firstName: "Carlos",
      lastName: "Ferreira",
      email: "carlos.ferreira@email.com",
      documentNumber: "789.123.456-00",
    },
    modalities: [
      {
        id: "mod-005",
        modality: {
          id: "mod-005",
          eventId: "event-1",
          name: "Corrida 10K",
          price: 130,
          isActive: true,
          order: 5,
          createdAt: "",
          updatedAt: "",
        },
      },
    ],
    kitItems: [],
    questionAnswers: [],
  },
  {
    id: "reg-006",
    eventId: "event-1",
    userId: "user-006",
    status: "CONFIRMED",
    totalAmount: 150,
    serviceFee: 7.5,
    finalAmount: 157.5,
    qrCode: "QR-006",
    purchaseDate: "2025-01-20T13:22:00Z",
    user: {
      id: "user-006",
      firstName: "Fernanda",
      lastName: "Lima",
      email: "fernanda.lima@email.com",
      documentNumber: "147.258.369-00",
    },
    modalities: [
      {
        id: "mod-001",
        modality: {
          id: "mod-001",
          eventId: "event-1",
          name: "Corrida 5K",
          price: 80,
          isActive: true,
          order: 1,
          createdAt: "",
          updatedAt: "",
        },
      },
      {
        id: "mod-006",
        modality: {
          id: "mod-006",
          eventId: "event-1",
          name: "Kit Premium",
          price: 70,
          isActive: true,
          order: 6,
          createdAt: "",
          updatedAt: "",
        },
      },
    ],
    kitItems: [],
    questionAnswers: [],
  },
  {
    id: "reg-007",
    eventId: "event-1",
    userId: "user-007",
    status: "CONFIRMED",
    totalAmount: 200,
    serviceFee: 10,
    finalAmount: 210,
    qrCode: "QR-007",
    purchaseDate: "2025-01-12T10:30:00Z",
    user: {
      id: "user-007",
      firstName: "Roberto",
      lastName: "Almeida",
      email: "roberto.almeida@email.com",
      documentNumber: "369.258.147-00",
    },
    modalities: [
      {
        id: "mod-003",
        modality: {
          id: "mod-003",
          eventId: "event-1",
          name: "Meia Maratona 21K",
          price: 200,
          isActive: true,
          order: 3,
          createdAt: "",
          updatedAt: "",
        },
      },
    ],
    kitItems: [],
    questionAnswers: [],
  },
  {
    id: "reg-008",
    eventId: "event-1",
    userId: "user-008",
    status: "CANCELLED",
    totalAmount: 80,
    serviceFee: 4,
    finalAmount: 84,
    qrCode: "QR-008",
    purchaseDate: "2025-01-22T15:45:00Z",
    user: {
      id: "user-008",
      firstName: "Juliana",
      lastName: "Ribeiro",
      email: "juliana.ribeiro@email.com",
      documentNumber: "852.963.741-00",
    },
    modalities: [
      {
        id: "mod-001",
        modality: {
          id: "mod-001",
          eventId: "event-1",
          name: "Corrida 5K",
          price: 80,
          isActive: true,
          order: 1,
          createdAt: "",
          updatedAt: "",
        },
      },
    ],
    kitItems: [],
    questionAnswers: [],
  },
];
